# Generated by Django 5.2.7 on 2025-10-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_email_alter_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terefas', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
