# Generated by Django 5.2.7 on 2025-10-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_tarefa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
