# Generated by Django 5.2.7 on 2025-10-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_tarefa_usuario_tarefa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('A fazer', 'A fazer'), ('Fazendo', 'Fazendo'), ('Pronto', 'Pronto')], default='A fazer', help_text='Status da tarefa', max_length=20),
        ),
    ]
